memory_limit = 256M
upload_max_filesize = 64M
post_max_size = 64M

; opcache ставится только в prod-стадии — в dev эти директивы игнорируются
opcache.enable = 1
opcache.memory_consumption = 96
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
