name: Deploy Laravel Project with Backup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
          
          echo "=== Checking server environment ==="
          command -v php >/dev/null 2>&1 || { echo >&2 "PHP not found! Aborting."; exit 1; }
          command -v composer >/dev/null 2>&1 || { echo >&2 "Composer not found! Aborting."; exit 1; }
          command -v mysql >/dev/null 2>&1 || { echo >&2 "MySQL client not found! Aborting."; exit 1; }
          command -v node >/dev/null 2>&1 || { echo >&2 "Node.js not found! Required for Vite build (Breeze/Inertia/Vue). Aborting."; exit 1; }
          command -v npm >/dev/null 2>&1 || { echo >&2 "npm not found! Required for Vite build. Aborting."; exit 1; }

          # Создаем папку для резервных копий, если не существует
          mkdir -p ~/db_backups

          cd ${{ secrets.PROJECT_PATH_MAIN }}

          echo "=== Pull latest code ==="
          git fetch --all
          git reset --hard origin/main

          echo "=== Install PHP dependencies ==="
          composer install --no-dev --optimize-autoloader

          echo "=== Backup database ==="
          BACKUP_FILE="backup_$(date +'%Y%m%d_%H%M%S').sql"
          mysqldump -u "${{ secrets.DB_USER }}" -p"${{ secrets.DB_PASSWORD }}" "${{ secrets.DB_NAME }}" > ~/db_backups/$BACKUP_FILE
          echo "Backup saved to ~/db_backups/$BACKUP_FILE"

          echo "=== Install Node dependencies and build assets (Vite) ==="
          # Ensure deterministic install using package-lock.json
          npm ci
          # Clean old Vite build to avoid stale assets
          rm -rf public/build
          # Build for production (Laravel Vite plugin outputs to public/build)
          npm run build

          echo "=== Run database migrations ==="
          if ! php artisan migrate --force; then
            echo "Migration failed! Check Laravel logs."
            exit 1
          fi

          echo "=== Clear and cache configuration, routes, views ==="
          php artisan config:clear
          php artisan config:cache
          php artisan route:clear
          php artisan route:cache || echo "Warning: Route cache failed, check route names!"
          php artisan view:clear
          php artisan view:cache
          php artisan optimize

          echo "=== Ensure storage symlink ==="
          if [ ! -L public/storage ]; then
            php artisan storage:link || true
          fi

          echo "=== Set file permissions ==="
          sudo chown -R www-data:www-data ${{ secrets.PROJECT_PATH_MAIN }}
          sudo chmod -R 775 ${{ secrets.PROJECT_PATH_MAIN }}/storage
          sudo chmod -R 775 ${{ secrets.PROJECT_PATH_MAIN }}/bootstrap/cache

          echo "=== Deploy finished successfully ==="
        EOF
